<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;h3&gt;Conditions G&amp;eacute;n&amp;eacute;rales de Vente&lt;/h3&gt;
&lt;h4&gt;1. Objet&lt;/h4&gt;
&lt;p&gt;Les pr&amp;eacute;sentes conditions g&amp;eacute;n&amp;eacute;rales d&amp;eacute;finissent les droits et obligations des parties dans le cadre de la r&amp;eacute;servation (y compris la r&amp;eacute;servation &amp;agrave; distance) de services propos&amp;eacute;s par l\'&amp;eacute;tablissement L&amp;rsquo;Amandari (repr&amp;eacute;sent&amp;eacute; par la SARL Amandari Consult) sur son Site et ses Services mobiles.&lt;/p&gt;
&lt;p&gt;Elles r&amp;eacute;gissent toutes les &amp;eacute;tapes n&amp;eacute;cessaires &amp;agrave; la r&amp;eacute;servation et au suivi de la r&amp;eacute;servation entre les parties contractantes.&lt;/p&gt;
&lt;p&gt;Toute r&amp;eacute;servation implique donc de la part du client l&amp;rsquo;adh&amp;eacute;sion enti&amp;egrave;re et sans r&amp;eacute;serve aux pr&amp;eacute;sentes conditions.&lt;/p&gt;
&lt;p&gt;Tout client reconna&amp;icirc;t avoir la capacit&amp;eacute; de contracter, c&amp;rsquo;est-&amp;agrave;-dire avoir la majorit&amp;eacute; l&amp;eacute;gale et ne pas &amp;ecirc;tre sous curatelle ou sous tutelle.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;****COVID-19****&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Dans cette p&amp;eacute;riode de crise sanitaire nous tenons &amp;agrave; informer nos clients de deux &amp;eacute;l&amp;eacute;ments sp&amp;eacute;cifiques de nos Conditions G&amp;eacute;n&amp;eacute;rales de Vente :&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;La flexibilit&amp;eacute; : Merci de bien lire l&amp;rsquo;article 8 des pr&amp;eacute;sentes CGV.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;La responsabilit&amp;eacute; : Merci de bien lire l&amp;rsquo;article 12 des pr&amp;eacute;sentes CGV.&lt;/strong&gt;&lt;/p&gt;
&lt;h4&gt;2. Champ d\'application&lt;/h4&gt;
&lt;p&gt;Les pr&amp;eacute;sentes conditions g&amp;eacute;n&amp;eacute;rales de vente s\'appliquent &amp;agrave; toutes les r&amp;eacute;servations conclues par internet, via le Site web ou les Services mobiles et de ses partenaires.&lt;/p&gt;
&lt;h4&gt;3. Opposabilit&amp;eacute; des conditions g&amp;eacute;n&amp;eacute;rales&lt;/h4&gt;
&lt;p&gt;En tout &amp;eacute;tat de cause, la version des conditions g&amp;eacute;n&amp;eacute;rales de vente opposable au client est celle en vigueur au moment de sa r&amp;eacute;servation sur le Site web ou les Services mobiles ou aupr&amp;egrave;s de ses partenaires.&lt;/p&gt;
&lt;h4&gt;4. R&amp;eacute;servation&lt;/h4&gt;
&lt;p&gt;Les r&amp;eacute;servations sont effectuables sur le site web, par t&amp;eacute;l&amp;eacute;phone, par e-mail ou par courrier.&lt;/p&gt;
&lt;p&gt;La r&amp;eacute;servation ne sera effective que si cette derni&amp;egrave;re est garantie par le client par le versement d&amp;rsquo;un acompte par carte de cr&amp;eacute;dit, cheque ou virement et apr&amp;egrave;s r&amp;eacute;ception d&amp;rsquo;une confirmation de r&amp;eacute;servation d&amp;eacute;taill&amp;eacute;e.&lt;/p&gt;
&lt;p&gt;Le r&amp;egrave;glement de l&amp;rsquo;ensemble des prestations se fera directement aupr&amp;egrave;s de l&amp;rsquo;&amp;eacute;tablissement (exceptions faites pour les r&amp;eacute;servations pr&amp;eacute;pay&amp;eacute;es comme les ch&amp;egrave;ques cadeau par ex. au moment de la r&amp;eacute;servation).&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;&amp;eacute;tablissement se r&amp;eacute;serve le droit de refuser toute r&amp;eacute;servation dans le cas o&amp;ugrave; le num&amp;eacute;ro de carte de cr&amp;eacute;dit serait incorrect ou la r&amp;eacute;servation incompl&amp;egrave;te.&lt;/p&gt;
&lt;p&gt;Les r&amp;eacute;servations quelles que soient leurs origines seront payables en euros uniquement.&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;&amp;eacute;tablissement accepte uniquement les cartes de cr&amp;eacute;dit suivantes : Visa, Mastercard et poss&amp;egrave;de un syst&amp;egrave;me de r&amp;eacute;servations s&amp;eacute;curis&amp;eacute;e (SSL) qui prot&amp;egrave;ge et crypte toutes les donn&amp;eacute;es sensibles transmises &amp;agrave; la r&amp;eacute;servation afin d&amp;rsquo;emp&amp;ecirc;cher toute divulgation &amp;agrave; un tiers.&lt;/p&gt;
&lt;p&gt;Lors de l&amp;rsquo;enregistrement de la r&amp;eacute;servation, un acompte de 30% (ou d&amp;rsquo;une nuit minimum pour tout s&amp;eacute;jour inf&amp;eacute;rieur &amp;agrave; 3 nuit&amp;eacute;es) pourra &amp;ecirc;tre pr&amp;eacute;lev&amp;eacute; sur la carte de cr&amp;eacute;dit communiqu&amp;eacute;e par le client.&lt;/p&gt;
&lt;p&gt;Si un r&amp;egrave;glement par carte de cr&amp;eacute;dit de l\'acompte n\'est pas possible, sur demande, un virement &amp;agrave; l\'ordre de Amandari Consult pourra &amp;ecirc;tre effectu&amp;eacute;.&lt;/p&gt;
&lt;p&gt;Dans le cas d&amp;rsquo;un virement bancaire, la r&amp;eacute;servation ne devient ferme et d&amp;eacute;finitive qu&amp;rsquo;&amp;agrave; r&amp;eacute;ception de l&amp;rsquo;acompte par l&amp;rsquo;&amp;eacute;tablissement, dans les d&amp;eacute;lais impartis.&lt;/p&gt;
&lt;p&gt;Le client est le seul responsable de son choix des services et de leur ad&amp;eacute;quation &amp;agrave; ses besoins, de telle sorte que la responsabilit&amp;eacute; de l&amp;rsquo;&amp;eacute;tablissement ne peut &amp;ecirc;tre recherch&amp;eacute;e &amp;agrave; cet &amp;eacute;gard.&lt;/p&gt;
&lt;h4&gt;5. Paiement&lt;/h4&gt;
&lt;p&gt;Le client doit se pr&amp;eacute;senter &amp;agrave; l\'&amp;eacute;tablissement avec la carte bancaire lui ayant permis de r&amp;eacute;aliser le paiement de l&amp;rsquo;acompte de 30%.&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;&amp;eacute;tablissement pourra &amp;eacute;galement lui demander de pr&amp;eacute;senter une pi&amp;egrave;ce d&amp;rsquo;identit&amp;eacute; &amp;agrave; des fins de pr&amp;eacute;vention des fraudes &amp;agrave; la carte bancaire.&lt;/p&gt;
&lt;p&gt;Le paiement du solde du s&amp;eacute;jour s&amp;rsquo;effectue &amp;agrave; l&amp;rsquo;arriv&amp;eacute;e &amp;agrave; l&amp;rsquo;&amp;eacute;tablissement lors du s&amp;eacute;jour, sauf dans le cas de conditions ou tarifs sp&amp;eacute;ciaux (ch&amp;egrave;ques cadeaux) o&amp;ugrave; le d&amp;eacute;bit du paiement s&amp;rsquo;effectue lors de la r&amp;eacute;servation (pr&amp;eacute;paiement en ligne sur certains tarifs). Ce pr&amp;eacute;paiement est qualifi&amp;eacute; d&amp;rsquo;acompte.&lt;/p&gt;
&lt;p&gt;Dans le cas d&amp;rsquo;un tarif non pr&amp;eacute;pay&amp;eacute; en ligne, l\'&amp;eacute;tablissement pourra demander au client, lors de son arriv&amp;eacute;e, un d&amp;eacute;p&amp;ocirc;t de garantie ou une autorisation de d&amp;eacute;biter la carte de cr&amp;eacute;dit, en vue de garantir le paiement des sommes correspondant aux prestations consomm&amp;eacute;es sur place.&lt;/p&gt;
&lt;p&gt;Le paiement du solde du s&amp;eacute;jour s&amp;rsquo;effectuera sur place aupr&amp;egrave;s de l&amp;rsquo;&amp;eacute;tablissement en esp&amp;egrave;ces, par ch&amp;egrave;que, par virement ou via des ch&amp;egrave;ques ANCV. Les cartes bancaires ne sont pas accept&amp;eacute;es.&lt;/p&gt;
&lt;h4&gt;6. Droit de r&amp;eacute;tractation&lt;/h4&gt;
&lt;p&gt;Il est rappel&amp;eacute; au client, conform&amp;eacute;ment &amp;agrave; l&amp;rsquo;article L. 121-21-8 12&amp;deg; du Code de la Consommation, qu&amp;rsquo;il ne dispose pas du droit de r&amp;eacute;tractation pr&amp;eacute;vu &amp;agrave; l&amp;rsquo;article L. 121-21 du Code de la Consommation.&lt;/p&gt;
&lt;p&gt;Les Conditions de Vente du tarif r&amp;eacute;serv&amp;eacute; pr&amp;eacute;cisent les modalit&amp;eacute;s d&amp;rsquo;annulation et/ou de modification de la r&amp;eacute;servation.&lt;/p&gt;
&lt;h4&gt;7. Modification de s&amp;eacute;jour&lt;/h4&gt;
&lt;p&gt;Toute modification de r&amp;eacute;servation devra faire l&amp;rsquo;objet d&amp;rsquo;une demande par email &amp;agrave; l&amp;rsquo;&amp;eacute;tablissement ou par t&amp;eacute;l&amp;eacute;phone. La demande ne deviendra effective qu&amp;rsquo;au moment o&amp;ugrave; l&amp;rsquo;&amp;eacute;tablissement aura confirm&amp;eacute; son acceptation par &amp;eacute;crit.&lt;/p&gt;
&lt;p&gt;En cas de modification de s&amp;eacute;jour, les conditions suivantes s&amp;rsquo;appliquent :&lt;/p&gt;
&lt;p&gt;&amp;ndash; En cas de non-pr&amp;eacute;sentation &amp;agrave; la date d&amp;rsquo;arriv&amp;eacute;e pr&amp;eacute;vue, la carte de cr&amp;eacute;dit du client sera d&amp;eacute;bit&amp;eacute;e du montant total du s&amp;eacute;jour.&lt;/p&gt;
&lt;p&gt;&amp;ndash; Tout s&amp;eacute;jour commenc&amp;eacute; est enti&amp;egrave;rement d&amp;ucirc;.&lt;/p&gt;
&lt;h4&gt;8. Annulation de s&amp;eacute;jour&lt;/h4&gt;
&lt;p&gt;Toute annulation de r&amp;eacute;servation devra faire l&amp;rsquo;objet d&amp;rsquo;une demande par courriel &amp;agrave; l&amp;rsquo;&amp;eacute;tablissement ou par t&amp;eacute;l&amp;eacute;phone. La demande ne deviendra effective qu&amp;rsquo;au moment o&amp;ugrave; l&amp;rsquo;&amp;eacute;tablissement aura confirm&amp;eacute; son acceptation par &amp;eacute;crit.&lt;/p&gt;
&lt;p&gt;En cas d&amp;rsquo;annulation de s&amp;eacute;jour, les conditions suivantes s&amp;rsquo;appliquent sauf cas de force majeure :&lt;/p&gt;
&lt;p&gt;&amp;ndash; Pour toute demande effectu&amp;eacute;e &amp;agrave; moins de 30 jours de la date d&amp;rsquo;arriv&amp;eacute;e pr&amp;eacute;vue, l&amp;rsquo;acompte de 30% ne sera pas restitu&amp;eacute;. Le s&amp;eacute;jour ne pourra pas&amp;nbsp;&amp;ecirc;tre report&amp;eacute; &amp;agrave; une date ult&amp;eacute;rieure sauf accord de la SARL Amandari Consult.&lt;/p&gt;
&lt;p&gt;&amp;ndash; En cas de non-pr&amp;eacute;sentation &amp;agrave; la date d&amp;rsquo;arriv&amp;eacute;e pr&amp;eacute;vue, la carte de cr&amp;eacute;dit du client sera d&amp;eacute;bit&amp;eacute;e du montant total du s&amp;eacute;jour.&lt;/p&gt;
&lt;p&gt;&amp;ndash; Tout s&amp;eacute;jour commenc&amp;eacute; est enti&amp;egrave;rement d&amp;ucirc;.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;****Dans le cas du COVID-19 l&amp;rsquo;&amp;eacute;tablissement accepte les modifications et annulations de s&amp;eacute;jour de derni&amp;egrave;re minute si un nouveau confinement ou une restriction de circulation devait &amp;ecirc;tre d&amp;eacute;cid&amp;eacute;e par le gouvernement. ****&lt;/strong&gt;&lt;/p&gt;
&lt;h4&gt;9. Force majeure&lt;/h4&gt;
&lt;p&gt;La force majeure s\'entend de tout &amp;eacute;v&amp;eacute;nement ext&amp;eacute;rieur aux parties pr&amp;eacute;sentant un caract&amp;egrave;re &amp;agrave; la fois impr&amp;eacute;visible, insurmontable et ext&amp;eacute;rieur aux parties qui emp&amp;ecirc;che soit le client, soit l\'&amp;eacute;tablissement d\'assurer tout ou partie des obligations pr&amp;eacute;vues au contrat.&lt;/p&gt;
&lt;p&gt;Sont consid&amp;eacute;r&amp;eacute;s comme cas de force majeure ou cas fortuit ceux habituellement reconnus par la jurisprudence des Cours et Tribunaux fran&amp;ccedil;ais.&lt;/p&gt;
&lt;p&gt;Chaque partie ne pourra &amp;ecirc;tre tenue responsable &amp;agrave; l\'&amp;eacute;gard de l\'autre partie en cas d\'inex&amp;eacute;cution de ses obligations r&amp;eacute;sultant d\'un &amp;eacute;v&amp;eacute;nement de force majeure.&lt;/p&gt;
&lt;p&gt;Il est express&amp;eacute;ment convenu que la force majeure suspend, pour les parties, l\'ex&amp;eacute;cution de leurs obligations r&amp;eacute;ciproques et que chaque partie supporte la charge des frais qui en d&amp;eacute;coulent.&lt;/p&gt;
&lt;h4&gt;10. Prix&lt;/h4&gt;
&lt;p&gt;Les prix sont indiqu&amp;eacute;s en Euros.&lt;/p&gt;
&lt;p&gt;La TVA est toujours comprise.&lt;/p&gt;
&lt;p&gt;Les prix indiqu&amp;eacute;s ne comprennent que les prestations strictement mentionn&amp;eacute;es dans la r&amp;eacute;servation (les petits d&amp;eacute;jeuners sont offerts lorsque cela est pr&amp;eacute;cis&amp;eacute;)&lt;/p&gt;
&lt;p&gt;Au prix mentionn&amp;eacute; dans la r&amp;eacute;servation seront ajout&amp;eacute;es, lors de la facturation, les prestations compl&amp;eacute;mentaires fournies par l&amp;rsquo;&amp;eacute;tablissement lors du s&amp;eacute;jour et, le cas &amp;eacute;ch&amp;eacute;ant, la taxe de s&amp;eacute;jour.&lt;/p&gt;
&lt;p&gt;Les prix applicables sont ceux en vigueur au jour de la r&amp;eacute;servation. Les &amp;eacute;tablissements, professionnels ind&amp;eacute;pendants, sont libres de faire varier leur prix &amp;agrave; tout moment. Seul le prix indiqu&amp;eacute; dans la confirmation de r&amp;eacute;servation est contractuel.&lt;/p&gt;
&lt;h4&gt;11. R&amp;eacute;clamations, litiges&lt;/h4&gt;
&lt;p&gt;Toute r&amp;eacute;clamation doit &amp;ecirc;tre formul&amp;eacute;e aupr&amp;egrave;s de l&amp;rsquo;&amp;eacute;tablissement et ce, dans un d&amp;eacute;lai de 7 jours &amp;agrave; compter de la date de s&amp;eacute;jour.&lt;/p&gt;
&lt;p&gt;&amp;Agrave; d&amp;eacute;faut de recours &amp;agrave; la proc&amp;eacute;dure de m&amp;eacute;diation conventionnelle ou &amp;agrave; tout mode alternatif de r&amp;egrave;glement des litiges dans un d&amp;eacute;lai de 30 jours, chacune des parties pourra saisir la juridiction judiciaire comp&amp;eacute;tente.&lt;/p&gt;
&lt;h4&gt;12. Responsabilit&amp;eacute;s&lt;/h4&gt;
&lt;p&gt;Il appartient &amp;agrave; l&amp;rsquo;&amp;Eacute;tablissement de prendre toutes garanties et toutes assurances n&amp;eacute;cessaires &amp;agrave; l&amp;rsquo;accueil du public dans son Etablissement et &amp;agrave; l&amp;rsquo;exercice de son activit&amp;eacute;.&lt;/p&gt;
&lt;p&gt;L\'&amp;eacute;tablissement met un coffre-fort &amp;agrave; disposition du client &amp;agrave; la r&amp;eacute;ception. L\'&amp;eacute;tablissement ne peut &amp;ecirc;tre tenu responsable en cas de vol ou perte de biens ou d\'objets.&lt;/p&gt;
&lt;p&gt;Le client doit assurer la garde de ses biens et mat&amp;eacute;riels. Le client devra informer l&amp;rsquo;&amp;eacute;tablissement de toute d&amp;eacute;gradation dont il serait &amp;agrave; l&amp;rsquo;origine. Il est responsable de l&amp;rsquo;ensemble des dommages caus&amp;eacute;s par son interm&amp;eacute;diaire et s&amp;rsquo;engage, en cas de d&amp;eacute;gradation des lieux mis &amp;agrave; disposition, (chambre, espaces communs tels que piscine, jacuzzi, jardin, salon, sanitaires) &amp;agrave; supporter les co&amp;ucirc;ts de remise en &amp;eacute;tat.&lt;/p&gt;
&lt;p&gt;Aussi tout comportement contraire aux bonnes m&amp;oelig;urs et &amp;agrave; l&amp;rsquo;ordre public am&amp;egrave;nera l&amp;rsquo;&amp;eacute;tablissement &amp;agrave; demander au client de quitter l&amp;rsquo;&amp;eacute;tablissement sans aucune indemnit&amp;eacute; et ou sans aucun remboursement si un r&amp;egrave;glement a d&amp;eacute;j&amp;agrave; &amp;eacute;t&amp;eacute; effectu&amp;eacute;. Dans le cas o&amp;ugrave; aucun r&amp;egrave;glement n&amp;rsquo;a encore &amp;eacute;t&amp;eacute; effectu&amp;eacute;, le client devra s&amp;rsquo;acquitter du prix total du s&amp;eacute;jour avant de quitter l&amp;rsquo;&amp;eacute;tablissement.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;****Dans le cas du COVID-19 l&amp;rsquo;&amp;eacute;tablissement s\'autorise le droit de refuser tout service compl&amp;eacute;mentaire impliquant un surcroit de risque malgr&amp;eacute; l&amp;rsquo;application des conditions sanitaires requises. Le client &amp;eacute;tant pr&amp;eacute;venu le paiement du s&amp;eacute;jour sera d&amp;ucirc; dans son int&amp;eacute;gralit&amp;eacute;. Dans le cas o&amp;ugrave; un client pr&amp;eacute;sente des sympt&amp;ocirc;mes pendant son s&amp;eacute;jour l&amp;rsquo;&amp;eacute;tablissement imposera un isolement dans sa chambre et une prise de temp&amp;eacute;rature. Si le client refuse ou si le client cache volontairement des sympt&amp;ocirc;mes, l&amp;rsquo;&amp;eacute;tablissement s&amp;rsquo;autorise &amp;agrave; lui refuser le service et &amp;agrave; mettre fin &amp;agrave; son s&amp;eacute;jour. Le reste du s&amp;eacute;jour sera d&amp;ucirc;. ****&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Le client s&amp;rsquo;engage &amp;agrave; n&amp;rsquo;inviter aucune personne tierce dans l&amp;rsquo;enceinte de l&amp;rsquo;&amp;eacute;tablissement, jardin et piscine compris. Le client ne pourra apporter de l&amp;rsquo;ext&amp;eacute;rieur ni boissons, ni denr&amp;eacute;es alimentaires sans autorisation pr&amp;eacute;alable de la direction. Le client s&amp;rsquo;engage &amp;agrave; faire respecter, par les participants et leurs invit&amp;eacute;s, l&amp;rsquo;ensemble des consignes et r&amp;egrave;glements de l&amp;rsquo;&amp;eacute;tablissement (notamment l&amp;rsquo;interdiction de fumer). Le client veillera &amp;agrave; ce que les participants ne perturbent pas l&amp;rsquo;exploitation de l&amp;rsquo;&amp;eacute;tablissement ni ne portent atteinte &amp;agrave; la s&amp;eacute;curit&amp;eacute; de l&amp;rsquo;&amp;eacute;tablissement ainsi que des personnes qui s&amp;rsquo;y trouvent.&lt;/p&gt;
&lt;p&gt;Sauf disposition expresse contraire, le client doit quitter la chambre et l\'&amp;eacute;tablissement avant 11h30 le jour de la fin de la r&amp;eacute;servation. Il n\'est pas permis de profiter du jardin, de la piscine et autres infrastructures de l\'&amp;eacute;tablissement apr&amp;egrave;s le check-out ni d\'ailleurs avant le check-in pr&amp;eacute;vu &amp;agrave; partir de 17h00 (et jusqu&amp;rsquo;&amp;agrave; 21h00). A d&amp;eacute;faut, il lui sera factur&amp;eacute; une nuit&amp;eacute;e suppl&amp;eacute;mentaire.&lt;/p&gt;
&lt;p&gt;Les animaux familiers sont accept&amp;eacute;s (dans les chambres) sous r&amp;eacute;serve de l&amp;rsquo;accord pr&amp;eacute;alable de l&amp;rsquo;&amp;eacute;tablissement et de versement d&amp;rsquo;un forfait de s&amp;eacute;jour.&lt;/p&gt;
&lt;p&gt;L\'&amp;eacute;tablissement Amandari propose un acc&amp;egrave;s WIFI gratuit permettant aux clients de se connecter &amp;agrave; internet. Le client s&amp;rsquo;engage &amp;agrave; ce que les ressources informatiques mises &amp;agrave; sa disposition par l&amp;rsquo;&amp;eacute;tablissement ne soient en aucune mani&amp;egrave;re utilis&amp;eacute;es &amp;agrave; des fins de reproduction, de repr&amp;eacute;sentation, de mise &amp;agrave; disposition ou de communication au public d&amp;rsquo;&amp;oelig;uvres ou d&amp;rsquo;objets prot&amp;eacute;g&amp;eacute;s par un droit d&amp;rsquo;auteur ou par un droit voisin, tels que des textes, images, photographies, &amp;oelig;uvres musicales, &amp;oelig;uvres audiovisuelles, logiciels et jeux vid&amp;eacute;o, sans l&amp;rsquo;autorisation des titulaires des droits pr&amp;eacute;vus aux livres Ier et II du code de la propri&amp;eacute;t&amp;eacute; intellectuelle lorsque cette autorisation est requise. Si le client ne se conforme pas aux obligations pr&amp;eacute;cit&amp;eacute;es, il risquerait de se voir reprocher un d&amp;eacute;lit de contrefa&amp;ccedil;on (article L.335-3 du code de la propri&amp;eacute;t&amp;eacute; intellectuelle), sanctionn&amp;eacute; par une amende de 300.000 euros et de trois ans d\'emprisonnement. Le client est par ailleurs tenu de se conformer &amp;agrave; la politique de s&amp;eacute;curit&amp;eacute; du fournisseur d&amp;rsquo;acc&amp;egrave;s internet de l&amp;rsquo;&amp;eacute;tablissement, y compris aux r&amp;egrave;gles d&amp;rsquo;utilisation des moyens de s&amp;eacute;curisation mis en &amp;oelig;uvre dans le but de pr&amp;eacute;venir l&amp;rsquo;utilisation illicite des ressources informatiques et de s&amp;rsquo;abstenir de tout acte portant atteinte &amp;agrave; l&amp;rsquo;efficacit&amp;eacute; de ces moyens.&lt;/p&gt;
&lt;p&gt;Les photographies pr&amp;eacute;sent&amp;eacute;es sur le Site et les Services mobiles de l&amp;rsquo;&amp;eacute;tablissement ou ceux des partenaires ont une valeur simplement indicative. M&amp;ecirc;me si tous les meilleurs efforts sont faits pour que les photographies, repr&amp;eacute;sentations graphiques et les textes reproduits pour illustrer les &amp;eacute;tablissements pr&amp;eacute;sent&amp;eacute;s donnent un aper&amp;ccedil;u aussi exact que possible des prestations d&amp;rsquo;h&amp;eacute;bergement propos&amp;eacute;es, des variations peuvent intervenir, notamment en raison du changement de mobilier ou de r&amp;eacute;novations &amp;eacute;ventuelles.&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;&amp;eacute;tablissement ne saurait &amp;ecirc;tre tenu pour responsable de l\'inex&amp;eacute;cution ou de la mauvaise ex&amp;eacute;cution de la r&amp;eacute;servation en cas de force majeure, du fait du tiers, impr&amp;eacute;visible et insurmontable, du fait du client, notamment l\'indisponibilit&amp;eacute; du r&amp;eacute;seau internet, impossibilit&amp;eacute; d&amp;rsquo;acc&amp;egrave;s au site web, intrusion ext&amp;eacute;rieure, virus informatiques ou en cas de pr&amp;eacute;paiement non autoris&amp;eacute; par la banque du porteur.&lt;/p&gt;
&lt;h4&gt;13. D&amp;eacute;logement&lt;/h4&gt;
&lt;p&gt;En cas d&amp;rsquo;&amp;eacute;v&amp;egrave;nement exceptionnel ou d&amp;rsquo;impossibilit&amp;eacute; de mettre la chambre r&amp;eacute;serv&amp;eacute;e &amp;agrave; disposition du client ou en cas de force majeure, l&amp;rsquo;&amp;eacute;tablissement remboursera le client des sommes d&amp;eacute;j&amp;agrave; vers&amp;eacute;es (restitution de l&amp;rsquo;acompte). En aucun cas, l&amp;rsquo;&amp;eacute;tablissement ne sera tenu de trouver un autre h&amp;eacute;bergement au client ni d&amp;rsquo;en assumer partiellement ou totalement les frais cons&amp;eacute;cutifs, ni de verser une quelconque indemnit&amp;eacute; au client.&lt;/p&gt;
&lt;p&gt;Crise sanitaire : Dans l\'&amp;eacute;ventualit&amp;eacute; d\'une crise sanitaire avec obligation de confinement et annulation des r&amp;eacute;servations, l\'&amp;eacute;tablissement appliquera le d&amp;eacute;cret mis en place par le gouvernement fran&amp;ccedil;ais dans pareille situation &amp;agrave; savoir l\'&amp;eacute;tablissement d\'un avoir correspondant au montant des sommes/acomptes vers&amp;eacute;s. Ces avoirs seront valables dans le d&amp;eacute;lai fix&amp;eacute; par ledit d&amp;eacute;cret. Un remboursement des r&amp;eacute;servations ou des acomptes d&amp;eacute;j&amp;agrave; vers&amp;eacute;s ne sera pas possible.&lt;/p&gt;
&lt;h4&gt;14. M&amp;eacute;diation&lt;/h4&gt;
&lt;p&gt;Le d&amp;eacute;cret du 30 octobre 2015 relatif &amp;agrave; la m&amp;eacute;diation des litiges de la consommation, qui transpose en droit fran&amp;ccedil;ais la directive 2013/11/UE du 21 mai 2013 relative au r&amp;egrave;glement extrajudiciaire des litiges de consommation, et l&amp;rsquo;ordonnance n&amp;deg; 2015-1033 du 20 ao&amp;ucirc;t 2015 relative au r&amp;egrave;glement extrajudiciaire des litiges de consommation, viennent pr&amp;eacute;ciser les conditions d&amp;rsquo;application de l&amp;rsquo;article L152-1 du Code de la consommation, qui oblige les professionnels de tous secteurs de la consommation &amp;agrave; proposer une proc&amp;eacute;dure de m&amp;eacute;diation en cas de litige avec leurs clients. Selon la loi, l&amp;rsquo;issue de la m&amp;eacute;diation doit intervenir dans un d&amp;eacute;lai de 90 jours. Nous vous invitons &amp;agrave; formuler vos demandes exclusivement par mail qui apporteront une datation de votre correspondance et d&amp;rsquo;en garder une archive personnelle.&lt;/p&gt;
&lt;p&gt;M&amp;eacute;diation interne&lt;/p&gt;
&lt;p&gt;Pour tous litiges n&amp;rsquo;ayant pas trouv&amp;eacute; de solutions, nous vous invitons &amp;agrave; joindre le service de M&amp;eacute;diation Interne, qui s&amp;rsquo;engage &amp;agrave; vous apporter une r&amp;eacute;ponse satisfaisante dans un d&amp;eacute;lai de 30 jours.&lt;/p&gt;
&lt;p&gt;En cas d&amp;rsquo;insatisfaction, il est port&amp;eacute; &amp;agrave; votre connaissance le recours aupr&amp;egrave;s d&amp;rsquo;un m&amp;eacute;diateur externe.&lt;/p&gt;
&lt;p&gt;M&amp;eacute;diation externe&lt;/p&gt;
&lt;p&gt;Nous avons d&amp;eacute;sign&amp;eacute; un m&amp;eacute;diateur ind&amp;eacute;pendant&amp;nbsp;:&lt;/p&gt;
&lt;p&gt;MTV &amp;ndash; la m&amp;eacute;diation tourisme et Voyage BP80303 &amp;ndash; 75823 Paris cedex 17.&lt;/p&gt;
&lt;p&gt;Pour plus de d&amp;eacute;tails, veuillez consulter son site internet &amp;agrave; l&amp;rsquo;adresse suivante&amp;nbsp;: https://www.mtv.travel&lt;/p&gt;
&lt;h4&gt;15. Droit applicable&lt;/h4&gt;
&lt;p&gt;Les pr&amp;eacute;sentes conditions de vente sont soumises &amp;agrave; la loi fran&amp;ccedil;aise et europ&amp;eacute;enne.&lt;/p&gt;
&lt;h3&gt;Mentions L&amp;eacute;gales&lt;/h3&gt;
&lt;h4&gt;Informations Juridiques&lt;/h4&gt;
&lt;p&gt;Sarl Amandari Consult- vallat d&amp;rsquo;Emponse &amp;ndash; 83120 Le Plan de la Tour&lt;/p&gt;
&lt;p&gt;T&amp;eacute;l. : +33 (0)6 09 15 63 86 Mail : amandari.chambredhote@gmail.com&lt;/p&gt;
&lt;p&gt;RCS : St Tropez 440&amp;nbsp;735&amp;nbsp;975 00011&amp;nbsp;&lt;/p&gt;
&lt;h4&gt;Illustrations et photos&lt;/h4&gt;
&lt;p&gt;Les textes et les illustrations de ce site sont la propri&amp;eacute;t&amp;eacute; de l&amp;rsquo;Amandari&lt;/p&gt;
&lt;h4&gt;H&amp;eacute;bergement du site&lt;/h4&gt;
&lt;p&gt;OVH&lt;/p&gt;
&lt;h4&gt;Loi informatique et libert&amp;eacute;s&lt;/h4&gt;
&lt;p&gt;Conform&amp;eacute;ment &amp;agrave; la loi \&quot;Informatique et Libert&amp;eacute;\&quot; n&amp;deg; 78-17 du 8 janvier 1978 relative &amp;agrave; l\'informatique, aux fichiers et aux libert&amp;eacute;s, vous disposez d\'un droit d\'acc&amp;egrave;s et de rectification sur les donn&amp;eacute;es nominatives que vous laissez sur ce site. Pour faire valoir ce droit, il vous suffit de nous contacter par email : amandari.chambredhote@gmail.com&lt;/p&gt;
&lt;p&gt;En outre nous nous engageons &amp;agrave; prendre toutes les pr&amp;eacute;cautions n&amp;eacute;cessaires afin de pr&amp;eacute;server la s&amp;eacute;curit&amp;eacute; de ces informations et notamment emp&amp;ecirc;cher qu\'elles ne soient d&amp;eacute;form&amp;eacute;es, endommag&amp;eacute;es ou communiqu&amp;eacute;es &amp;agrave; des tiers, personne physique ou morale&lt;/p&gt;
&lt;h4&gt;Politique de confidentialit&amp;eacute;&lt;/h4&gt;
&lt;p&gt;Nous recueillons des informations lorsque vous consultez notre site. Les informations recueillies par la page contact incluent votre nom, votre adresse e-mail, num&amp;eacute;ro de t&amp;eacute;l&amp;eacute;phone. Ces informations sont recueillies dans le seul but de r&amp;eacute;pondre &amp;agrave; votre demande. Nous utilisons l&amp;rsquo;adresse e-mail que vous fournissez pour vous envoyer des informations et notifications, des nouvelles de l&amp;rsquo;Amandari occasionnellement. Si &amp;agrave; n&amp;rsquo;importe quel moment vous souhaitez-vous d&amp;eacute;sinscrire et ne plus recevoir d&amp;rsquo;e-mails, envoyez-nous votre demande &amp;agrave; amandari.chambredhote@gmail.com et nous effacerons vos informations de nos fichiers.&lt;/p&gt;
&lt;p&gt;Nous sommes les seuls propri&amp;eacute;taires des informations recueillies sur ce site. Vos informations personnelles ne seront pas vendues, &amp;eacute;chang&amp;eacute;es, transf&amp;eacute;r&amp;eacute;es, ou donn&amp;eacute;es &amp;agrave; une autre soci&amp;eacute;t&amp;eacute; pour n&amp;rsquo;importe quelle raison, sans votre consentement. Nous mettons tout en &amp;oelig;uvre pour pr&amp;eacute;server la s&amp;eacute;curit&amp;eacute; de vos informations personnelles.&lt;/p&gt;
&lt;p&gt;D&amp;egrave;s lors que vous quittez le site de l&amp;rsquo;Amandari ou que vous &amp;ecirc;tes redirig&amp;eacute; vers le site web ou l&amp;rsquo;application d&amp;rsquo;un tiers, vous n&amp;rsquo;&amp;ecirc;tes plus r&amp;eacute;gi par la pr&amp;eacute;sente Politique de Confidentialit&amp;eacute; ni par les Conditions G&amp;eacute;n&amp;eacute;rales d&amp;rsquo;Utilisation de notre site web.&lt;/p&gt;";

$champ_2="";

$champ_3="";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

?>
