<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;p&gt;&lt;span style=\&quot;color: #ff0000; font-family: tahoma, arial, helvetica, sans-serif; font-size: 10pt;\&quot;&gt;&lt;strong&gt;En septembre, nous vous pretons gracieusement nos velos electriques, pour decouvrir autrement le massif des Maures !&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;";

$champ_2="&lt;p&gt;&lt;span style=\&quot;color: #ff0000; font-family: arial, helvetica, sans-serif;\&quot;&gt;&lt;span style=\&quot;font-size: 16px;\&quot;&gt;&lt;strong&gt;In september, we will offer to borrow our 2 electric bikes, in order to discover the area&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;";

$champ_3="&lt;div class=\&quot;main tarifs\&quot;&gt;&lt;!--#include virtual=\&quot;modif.php?affich=champ_3\&quot;--&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Tarifs 2021 CHAMBRES D\'H&amp;Ocirc;TES &lt;/strong&gt;Prix en euros / nuit ( petit-d&amp;eacute;jeuners inclus)&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;haute saison&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;du 03/07 au 04/09/2021&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/div&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;du 03/04 au 02/07 &lt;/strong&gt;&lt;/div&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;et du 05/09 au 03/10/21&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;basse saison&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;Chambre Amande&lt;/strong&gt; (2 personnes)&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;130 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;110&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;Chambre Romarin&lt;/strong&gt; (2 personnes)&lt;br /&gt; Suppl&amp;eacute;ment 3eme personne &lt;em&gt;(lit banquette&lt;/em&gt;)&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;br /&gt; + 30&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;130 &amp;euro;&lt;/p&gt;
&lt;p&gt;+ 25 e&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;110 &amp;euro;&lt;/strong&gt;&lt;br /&gt; &lt;strong&gt;+ 20&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;Chambre Lavande&lt;/strong&gt; (2 personnes)&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;140 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;120 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;100&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;Chambre Olive&lt;/strong&gt; (1 ou 2 personnes)&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;110&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;95 - 100 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;85-90&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;Suite familiale Mimosa&lt;/strong&gt; &lt;em&gt;(&lt;/em&gt;&lt;em&gt;3 ou 4 personnes -2 chambres communicantes)&lt;/em&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;190 - 200 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;180 -190 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;160-170&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;&amp;bull; D&amp;icirc;ner (sur reservation de minimum 6 personnes)&amp;nbsp;: &lt;strong&gt;35 &amp;euro;&lt;/strong&gt;&lt;br /&gt; &amp;bull; Chien admis&amp;nbsp;: &lt;strong&gt;&amp;nbsp; &lt;/strong&gt;&lt;strong&gt;de 5 &amp;agrave; 10&amp;nbsp;&amp;euro; / jour (selon taille)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;* Sous r&amp;eacute;serve de nos offres exceptionnelles.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;les chambres sont non fumeurs.&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Lors de la r&amp;eacute;servation, un acompte de 30% du s&amp;eacute;jour, avec un minimum d\'une nuit&amp;eacute;e vous sera demand&amp;eacute; par carte bancaire.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;En cas de s&amp;eacute;jour &amp;eacute;court&amp;eacute;, le prix correspondant au co&amp;ucirc;t du sejour reste int&amp;eacute;gralement acquis au propri&amp;eacute;taire. Le paiement du solde est &amp;agrave; verser &amp;agrave; l\'arriv&amp;eacute;e.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Les arriv&amp;eacute;es de font strictement entre 17 et 20 heures (sauf accord pr&amp;eacute;alable). Les d&amp;eacute;parts se font avant 12H00. Un suppl&amp;eacute;ment forfaitaire de 30 euros sera appliqu&amp;eacute; pour toute arriv&amp;eacute;e ou tout d&amp;eacute;part en dehors de ces horaires.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;em&gt;&amp;bull; Au del&amp;agrave; de 3 nuit&amp;eacute;es reserv&amp;eacute;es (&amp;agrave; partir de la 4eme nuit), une remise de 10&amp;nbsp;&amp;euro; par nuit est accord&amp;eacute;e sur le tarif par nuit&amp;eacute;e sauf en Juillet et Aout&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;En Juillet et Aout, une majoration de 30&amp;nbsp;&amp;euro; par nuit sera appliqu&amp;eacute;e pour tout&amp;nbsp; s&amp;eacute;jour inferieur &amp;agrave; 2 nuit&amp;eacute;es,&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;t&amp;eacute;l&amp;eacute;phoner&lt;/a&gt; &lt;a href=\&quot;reservation.php\&quot;&gt;r&amp;eacute;server par email&lt;/a&gt;&lt;/div&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Tarifs 2021 ROULOTTE &lt;/strong&gt;Prix en euros / nuit&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;haute saison&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;basse saison&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;Roulotte&lt;/strong&gt; (1 ou 2 personnes)&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;120 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;100 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;br /&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot; align=\&quot;center\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Tarifs 2021 GITE &lt;/strong&gt;Prix en euros / semaine&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;Basse &lt;br /&gt; saison&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;Moyenne &lt;br /&gt; saison&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;Haute&lt;br /&gt; saison&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;Gite Maxi &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(8 pers maxi)&lt;/em&gt;&lt;br /&gt; 2&amp;nbsp; chambres avec douche&amp;nbsp; + WC, &lt;br /&gt; 1 chambre en mezzanine avec salle de bains + wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;800&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+50&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1350&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80 &amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;2050&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+100 &amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;Gite Midi &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(5 pers maxi)&lt;/em&gt;&lt;br /&gt; 1&amp;nbsp; chambre avec douche&amp;nbsp; + WC, &lt;br /&gt; 1 chambre en mezzanine avec salle de bains + wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;740&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+40&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;980&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+60&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1400&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;Gite Mini &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;&amp;nbsp;(4 pers maxi)&lt;/em&gt;&lt;br /&gt; 1 chambre en mezzanine avec salle de bains &amp;nbsp;+ wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;460&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+30&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;Non Lou&amp;eacute;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;Non Lou&amp;eacute;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linge de maison fourni, lits faits &amp;agrave; l\'arriv&amp;eacute;e.&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Basse saison : reste de l\'ann&amp;eacute;e&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Moyenne saison : du 03/04/21 au 02/07/2021 et du 05/09 au 03/10/2021, &amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Haute saison : du 03/07 au 04/09/2021&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;En moyenne et basse saison, tarifs hors charges electricit&amp;eacute; (chauffage)&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot; align=\&quot;center\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Tarifs 2021 MAZET &lt;/strong&gt;Prix en euros / nuit&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;haute saison&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;basse saison&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&amp;nbsp;maisonnette independante pour 2 personnes&lt;/p&gt;
&lt;p&gt;1 chambre avec Tv et petit coin salon, 1 cuisine et son espace repas,&lt;/p&gt;
&lt;p&gt;1salle de douche avec WC, terrasse avec salon de jardin et de repas,&lt;/p&gt;
&lt;p&gt;forfait m&amp;eacute;nage&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;130 &amp;euro;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;110 &amp;euro;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;95 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;&lt;strong&gt;Basse saison : reste de l\'ann&amp;eacute;e&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Moyenne saison : du 03/04/21 au 02/07/2021 et du 05/09 au 03/10/2021, &amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Haute saison : du 03/07 au 04/09/2021&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;En moyenne &amp;amp; haute saison : minimum 3 nuits&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Remise de 10% pour un sejour de minimum 7 nuits en basse et moyenne saison&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;A partir de la 3eme nuit&amp;eacute;e reserv&amp;eacute;e, une remise de 10&amp;euro; est accord&amp;eacute;e sur le tarif/nuit (sauf juillet/aout)&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;t&amp;eacute;l&amp;eacute;phoner&lt;/a&gt; &lt;a href=\&quot;reservation.php\&quot;&gt;r&amp;eacute;server par email&lt;/a&gt;&lt;/div&gt;";

$champ_4="&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Rates 2021 AMANDARI (BREAKFASTS INCLUDED)&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;high season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;from 03/07 to 04/09/2021&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;mid season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;from 03/04 to 02/07&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;amp; 05/09 to 03/10/21&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;low season&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;Room Amande ( 2 persons)&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;140&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;130 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;110&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;Room Romarin ( 2 persons );extra bed&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;140&amp;nbsp;&amp;euro; + 30&amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;130+ 25 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;110 &amp;euro; +20&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;Room Lavande ( 2 persons )&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;140 &amp;euro; &amp;nbsp;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;120 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;100 &amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;Room Olive ( 1 or 2 persons )&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;110 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;95 - 100 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;85-90&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;Family Room ( 3 or 4 persons)two communicating rooms&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;200&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;180-190 e&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;160-170&amp;nbsp;&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;ul&gt;
&lt;ul&gt;
&lt;li&gt;Dinner upon reservation 6 guests requested : 35 &amp;euro;&lt;/li&gt;
&lt;li&gt;Dogs allowed with previous agreement :5/10&amp;nbsp;&amp;euro; / day ( according to size )&lt;/li&gt;
&lt;/ul&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;em&gt;&lt;strong&gt;&amp;bull; Over&amp;nbsp;&lt;/strong&gt;&lt;strong&gt;&amp;nbsp;3 nights booked, a special discount of &amp;nbsp;10&amp;nbsp;&amp;euro; / night will be granted except in July and August.&lt;/strong&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;nbsp;In July and August, a 30&amp;euro; overcharge/night will be asked for any stay under 2 nights.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;nbsp;When booking, a deposit of 30% of the stay, with a minimum of one night will be required by credit card.&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;phone&lt;/a&gt; &lt;a href=\&quot;reservation-en.php\&quot;&gt;book by email&lt;/a&gt;&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Rates 2021 Caravan &lt;/strong&gt;Price in EUR / night&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;high season&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;mid season&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;low season&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;Gipsy Caravan&lt;/strong&gt; (2 people)&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&amp;nbsp;120 &amp;euro;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;100 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;p&gt;&lt;strong&gt;The rooms are non smoking.&lt;/strong&gt; &lt;br /&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p&gt;In case of shortened stay, the price for the cost of living remains entirely due to &amp;nbsp;the owner. &lt;br /&gt;The balance has tobe paid upon arrival.&lt;/p&gt;
&lt;p&gt;Arrivals are strictly between 5:00 p.m. and 8:00 p.m (except prior agreement). Departures are before 12:00.&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt;if your arrival or departure is out of this time, we will ask for an additional fee : 30&amp;nbsp;&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot; align=\&quot;center\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Rates 2021 COTTAGE &lt;/strong&gt;Price in EUR / week&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;Low &lt;br /&gt; season&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;Middle&amp;nbsp;&lt;br /&gt; season &lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;div align=\&quot;center\&quot;&gt;&lt;strong&gt;High&lt;br /&gt; season&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;Maxi cottage&lt;/strong&gt; &lt;br /&gt; &lt;em&gt;(8 people max)&lt;/em&gt; &lt;br /&gt; 2 bedrooms with shower and toilet, &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;800&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+50&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1350&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;2050&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+100&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;&amp;nbsp;Midi cottage&lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(5 people max)&lt;/em&gt; &lt;br /&gt; 1 bedroom with shower and toilet, &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;740&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+40&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;980&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+60&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1400&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;strong&gt;Mini Cottage&lt;/strong&gt; &lt;br /&gt; &lt;em&gt;(4 people max)&lt;/em&gt; &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;p align=\&quot;center\&quot;&gt;&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&lt;strong&gt;460&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+30&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot;&gt;&lt;strong&gt;Not Rented&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot;&gt;&lt;strong&gt;Not Rented&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linen provided - Beds are prepared upon arrival&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Low season : other periods&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Middle season : from 03/04 to 02/07/2021, from 05/09 to 03/10/2021,&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;High season : from 03/07/2021 to 04/09/2021&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Medium and low season rates excluding &amp;nbsp;electricity charges (heating)&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;table border=\&quot;0\&quot; cellpadding=\&quot;4\&quot; align=\&quot;center\&quot;&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong&gt;Rates &lt;/strong&gt;2021 MAZET&amp;nbsp;&lt;/strong&gt;Price in EUR / week&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;&lt;strong&gt;High&lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;&lt;strong&gt;Middle&amp;nbsp;&lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;&lt;strong&gt;&lt;strong&gt;Low &lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;&amp;nbsp;independant cottage for 2 persons&lt;/p&gt;
&lt;p&gt;1 bedroom with TV and lounge corner, 1 kitchen&amp;nbsp; sand meal room ,&lt;/p&gt;
&lt;span class=\&quot;tlid-translation translation\&quot; lang=\&quot;en\&quot;&gt;&lt;span title=\&quot;\&quot;&gt;1 shower room with WC, terrace with garden furniture and dining,&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span title=\&quot;\&quot;&gt;cleaning fee&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;130 &amp;euro;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;+30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;
&lt;p&gt;110 &amp;euro;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;+30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td align=\&quot;center\&quot; bgcolor=\&quot;#414654\&quot;&gt;95 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linen provided - Beds are prepared upon arrival&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Low season : other periods&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Middle season : from 03/04 to 02/07/2021, from 05/09 to 03/10/2021,&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;High season : from 03/07/2020 to 04/09/2021&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Medium and low season rates excluding &amp;nbsp;electricity charges (heating)&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Minimum 3 nights stay in middle and high seasons&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;10%discount over 7 nights stay in low and middle seasons&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;phone&lt;/a&gt; &lt;a href=\&quot;reservation-en.php\&quot;&gt;book by email&lt;/a&gt;&lt;/div&gt;";

$champ_5="&lt;h3 class=\&quot;center\&quot; style=\&quot;margin-bottom: 16px;\&quot;&gt;CHARTE SANITAIRE&lt;/h3&gt;
&lt;p class=\&quot;center\&quot; style=\&quot;margin-bottom: 16px;\&quot;&gt;Mesures pr&amp;eacute;ventives Covid-19&lt;/p&gt;
&lt;div class=\&quot;covid19\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Nous avons la chance d\'&amp;ecirc;tre une petite structure avec une capacit&amp;eacute; d\'accueil r&amp;eacute;duite et donc des risques limit&amp;eacute;s.&lt;/p&gt;
&lt;p&gt;Nous nous engageons &amp;agrave; mettre en place, &amp;agrave; respecter et faire respecter des mesures adapt&amp;eacute;es pour r&amp;eacute;duire les risques d&amp;rsquo;infection dans la plus large mesure pour que vos vacances chez nous constituent une r&amp;eacute;elle d&amp;eacute;tente !&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Accueil personnalis&amp;eacute; sur rendez-vous&lt;/li&gt;
&lt;li&gt;Petits d&amp;eacute;jeuners de mani&amp;egrave;re individuelle devant votre chambre&lt;/li&gt;
&lt;li&gt;piscine accessible simultan&amp;eacute;ment pour 4 personnes (jacuzzi, limit&amp;eacute; &amp;agrave; 2 personnes)&lt;/li&gt;
&lt;li&gt;D&amp;eacute;sinfection des chambres &amp;agrave; chaque changement et des espaces communs quotidiennement et/ou selon l&amp;rsquo;usage&lt;/li&gt;
&lt;li&gt;Mise &amp;agrave; disposition de gel hydroalcoolique&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;Nous vous souhaitons un agr&amp;eacute;able s&amp;eacute;jour dans notre belle r&amp;eacute;gion.&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;img src=\&quot;photos/accueil-fmodale.jpg\&quot; alt=\&quot;amandari\&quot; /&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;h3&gt;CHARTE SANITAIRE COVID-19, en d&amp;eacute;tails &amp;hellip;&lt;/h3&gt;
&lt;p&gt;Distanciation physique en toute convivialit&amp;eacute;&lt;/p&gt;
&lt;p&gt;Nous &amp;eacute;talons les arriv&amp;eacute;es et les d&amp;eacute;parts de nos h&amp;ocirc;tes pour &amp;eacute;viter les rassemblements de plus de quatre personnes et vous demanderons de respecter les horaires convenus ensemble pour vos arriv&amp;eacute;es et d&amp;eacute;parts.&lt;/p&gt;
&lt;p&gt;Les petits d&amp;eacute;jeuners sous forme de buffet ou par grandes tabl&amp;eacute;es sont impossibles. Rassurez-vous, l&amp;rsquo;ensemble de nos bons produits restent disponibles mais ils vous seront propos&amp;eacute;s sur des plateaux individuels (nous vous proposerons une fiche &amp;agrave; remplir la veille avec votre choix). Nous vous demanderons de bien vouloir prendre votre petit d&amp;eacute;jeuner sur la table individuelle situ&amp;eacute;e devant votre chambre et nous rapporter votre plateau tout de suite apr&amp;egrave;s le petit d&amp;eacute;jeuner.&lt;/p&gt;
&lt;p&gt;En cas de mauvais temps, nous &amp;eacute;tablirons un planning, afin de le servir dans la pi&amp;egrave;ce commune en respectant la distanciation physique n&amp;eacute;cessaire.&lt;/p&gt;
&lt;p&gt;Nous limitons &amp;agrave; 4 personnes le nombre de personnes utilisant simultan&amp;eacute;ment la piscine(*) et les plages piscines.&lt;/p&gt;
&lt;p&gt;Par ailleurs, des transats sont &amp;agrave; disposition (par 2) dans diff&amp;eacute;rents espaces du jardin.&lt;/p&gt;
&lt;p&gt;Le jacuzzi sera accessible sur demande, pour une p&amp;eacute;riode limit&amp;eacute;e &amp;agrave; 1 heure par chambre, pour 2 personnes maximum (de mani&amp;egrave;re &amp;agrave; ce que nous puissions proc&amp;eacute;der &amp;agrave; la d&amp;eacute;sinfection d&amp;rsquo;usage)&lt;/p&gt;
&lt;h3&gt;Hygi&amp;egrave;ne des lieux&lt;/h3&gt;
&lt;p&gt;Nous respectons dans la mesure du possible une p&amp;eacute;riode d&amp;rsquo;inoccupation de 24 heures entre deux r&amp;eacute;servations d&amp;rsquo;une m&amp;ecirc;me chambre&lt;/p&gt;
&lt;p&gt;Le linge de maison (draps, serviettes) est syst&amp;eacute;matiquement lav&amp;eacute; &amp;agrave; 60&amp;deg;C au minimum avec l&amp;rsquo;ajout d&amp;rsquo;un produit d&amp;eacute;sinfectant&lt;/p&gt;
&lt;p&gt;Nous mettons &amp;agrave; votre disposition dans les espaces communs du mat&amp;eacute;riel de d&amp;eacute;sinfection (gel hydroalcoolique, lingettes, mouchoirs en papier, etc.). nous vous remercions de bien vouloir vous munir de vos propres masques de protection&lt;/p&gt;
&lt;h3&gt;Hygi&amp;egrave;ne des personnes&lt;/h3&gt;
&lt;p&gt;Nous restons toujours disponibles pour vous conseiller et vous servir. Nous nous engageons &amp;agrave; le faire en respectant les &amp;laquo; gestes barri&amp;egrave;re &amp;raquo; et, en particulier, &amp;agrave; nous laver les mains r&amp;eacute;guli&amp;egrave;rement et &amp;agrave; porter un masque lors de toute interaction avec vous (accueil, service, etc.), si vous le souhaitez.&lt;/p&gt;
&lt;h3&gt;Hygi&amp;egrave;ne collective&lt;/h3&gt;
&lt;p&gt;Parce qu&amp;rsquo;aucune mesure ne sera pleinement efficace sans la coop&amp;eacute;ration de tous :&lt;/p&gt;
&lt;p&gt;Nous exigeons de tous le respect scrupuleux des &amp;laquo; gestes barri&amp;egrave;re &amp;raquo; et, en particulier, des mesures de distanciation ainsi que des prescriptions sanitaires pour l&amp;rsquo;usage des parties communes et &amp;eacute;quipements mis &amp;agrave; la disposition de tous.&lt;/p&gt;
&lt;p&gt;Nous exigeons de tous le respect scrupuleux des r&amp;egrave;gles mises en place pour l&amp;rsquo;usage des parties communes, de la piscine(*) et des autres &amp;eacute;quipements.&lt;/p&gt;
&lt;p&gt;Pour la protection des personnes qui vous accueillent et entretiennent la maison, nous vous demanderons de contribuer un peu &amp;agrave; la d&amp;eacute;sinfection des &amp;eacute;quipements que vous utiliserez (par exemple en passant une lingette sur le bouton de la machine apr&amp;egrave;s vous &amp;ecirc;tre fait un caf&amp;eacute;).&lt;/p&gt;
&lt;p&gt;(*)&amp;nbsp;Sous r&amp;eacute;serve de la lev&amp;eacute;e de la fermeture obligatoire actuellement applicable &amp;agrave; toutes les piscines collectives dans le d&amp;eacute;partement du Var conform&amp;eacute;ment &amp;agrave; l&amp;rsquo;arr&amp;ecirc;t&amp;eacute; pr&amp;eacute;fectoral du 8 avril 2020&lt;/p&gt;";

$champ_6="&lt;h3 class=\&quot;center\&quot; style=\&quot;margin-bottom: 16px;\&quot;&gt;COVID-19 HEALTH CHARTER&lt;/h3&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;We are lucky to be a small structure with a reduced capacity and therefore limited risks. We are committed to implementing, respecting and enforcing appropriate measures to reduce the risk of infection to the greatest extent so that your vacation with us is a real relaxation!&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;personalized welcome by appointment&lt;/li&gt;
&lt;li&gt;breakfasts individually in front of your room.&lt;/li&gt;
&lt;li&gt;swimming pool accessible simultaneously for 4 people (jacuzzi, limited to 2 people)&lt;/li&gt;
&lt;li&gt;Disinfection of rooms at each change and common areas daily and / or according to use&lt;/li&gt;
&lt;li&gt;Provision of hydroalcoholic gel&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;We wish you a pleasant stay in our beautiful region&amp;hellip;&lt;/p&gt;
&lt;div&gt;&lt;img src=\&quot;photos/accueil-fmodale.jpg\&quot; alt=\&quot;amandari\&quot; /&gt;&lt;/div&gt;
&lt;h3&gt;COVID-19 HEALTH CHARTER, in details&amp;hellip;&amp;hellip;&lt;/h3&gt;
&lt;p&gt;Physical distance in a friendly atmosphere&lt;/p&gt;
&lt;p&gt;We stagger the arrivals and departures of our hosts to avoid gatherings of more than four people and will ask you to respect the times agreed together for your arrivals and departures.&lt;/p&gt;
&lt;p&gt;Breakfasts in the form of a buffet or in large table are impossible.&lt;/p&gt;
&lt;p&gt;Be sure anyway that all of our good products remain available but they will be offered to you on individual trays (we will propose you a sheet to fill out the day before with your choice).&lt;/p&gt;
&lt;p&gt;We will ask you to take your breakfast on the individual table in front of your room and bring us your tray immediately after breakfast.&lt;/p&gt;
&lt;p&gt;In case of bad weather, we will establish a schedule, in order to serve it in the common room while respecting the necessary physical distance.&lt;/p&gt;
&lt;p&gt;We limit to 4 people the number of people using simultaneously the swimming pool (as soon as it is no more prohibited!) and the swimming pool&amp;rsquo;s chairs&lt;br /&gt;In addition, deckchairs are available (in pairs) in different areas of the garden.&lt;/p&gt;
&lt;p&gt;The jacuzzi will be accessible on request, for a period limited to 1 hour per room, for a maximum of 2 people (so that we can carry out the usual disinfection)&lt;/p&gt;
&lt;h3&gt;Site hygiene&lt;/h3&gt;
&lt;p&gt;We will respect as much as possible a 24-hour vacancy period between two bookings for the same room.&lt;/p&gt;
&lt;p&gt;We carry out a &amp;ldquo;reinforced&amp;rdquo; cleaning including the usual cleaning phase supplemented by a systematic disinfection of the surfaces and manipulable accessories located in the rooms and the common parts (buttons of doors and shutters, edges of doors, coat hooks, switches, remote controls , screens, keys, etc.)&lt;/p&gt;
&lt;p&gt;Household linen (sheets, towels) is systematically washed at a minimum of 60 &amp;deg; C with the addition of a disinfectant.&lt;/p&gt;
&lt;p&gt;We provide disinfection equipment in the common areas (hydroalcoholic gel, wipes, tissues, etc.). thank you for bringing your own protective masks.&lt;/p&gt;
&lt;h3&gt;People &amp;lsquo;s Personal hygiene&lt;/h3&gt;
&lt;p&gt;We are always available to advise and serve you. We undertake to do so by respecting the &amp;ldquo;barrier gestures&amp;rdquo; and, in particular, to wash our hands regularly and to wear a mask when interacting with you (reception, service, etc.) if you wish.&lt;/p&gt;
&lt;h3&gt;Collective hygiene&lt;/h3&gt;
&lt;p&gt;Because no measure will be fully effective without everyone\'s cooperation:&lt;/p&gt;
&lt;p&gt;We demand from all scrupulous respect for \&quot;barrier gestures\&quot; and, in particular, distancing measures as well as sanitary prescriptions for the use of common areas and equipment made available to all.&lt;/p&gt;
&lt;p&gt;We require everyone to scrupulously respect the rules put in place for the use of common areas, the swimming pool&amp;nbsp; and other equipment.&lt;/p&gt;
&lt;p&gt;For the protection of the people who welcome you and maintain the house, we will ask you to contribute a little to the disinfection of the equipment that you will use (for example by passing a wipe on the button of the machine after making yourself a coffee).&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

?>
