<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Tarifs 2022 CHAMBRES D\'H&amp;Ocirc;TES&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Prix en euros/nuit* ( petit-d&amp;eacute;jeuners inclus)&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;div&gt;&lt;strong&gt;haute saison&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;du 1er/07 au 16/09/2022&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;div&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;du 1er/04 au 30/06;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;du 17/09 au 30/09&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;et du 22/10 au 13/11/22&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;div&gt;&lt;strong&gt;basse saison&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Chambre Amande&lt;/strong&gt; (2 personnes)&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;&amp;nbsp;130 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;120&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Chambre Romarin&lt;/strong&gt; (2 personnes)&lt;br /&gt; Suppl&amp;eacute;ment 3eme personne &lt;em&gt;(lit banquette&lt;/em&gt;)&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;br /&gt; + 30&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;130 &amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;+ 25 e&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;120 &amp;euro;&lt;/strong&gt;&lt;br /&gt; &lt;strong&gt;+ 20&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Chambre Lavande&lt;/strong&gt; (2 personnes)&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;140 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;125 &amp;euro;&amp;nbsp;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;120&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Chambre Olive&lt;/strong&gt; (1 ou 2 personnes)&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;120 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;95 - 110 &amp;euro;&amp;nbsp;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;90-100&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;Suite familiale Miel &amp;amp; Mimosa&lt;/strong&gt; &lt;em&gt;(&lt;/em&gt;&lt;em&gt;3 ou 4 personnes -2 chambres communicantes)&lt;/em&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;190 - 200 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;&amp;nbsp;185 -195 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;180-190&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;&amp;bull; D&amp;icirc;ner (sur reservation de minimum 6 personnes)&amp;nbsp;: &lt;strong&gt;35 &amp;euro;&lt;/strong&gt;&lt;br /&gt; &amp;bull; Chien admis&amp;nbsp;: &lt;strong&gt;&amp;nbsp; &lt;/strong&gt;&lt;strong&gt;de 5 &amp;agrave; 10&amp;nbsp;&amp;euro; / jour (selon taille)&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;* Sous r&amp;eacute;serve de nos offres exceptionnelles.&amp;nbsp;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;les chambres sont non fumeurs.&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Lors de la r&amp;eacute;servation, un acompte de 30% du s&amp;eacute;jour, avec un minimum d\'une nuit&amp;eacute;e vous sera demand&amp;eacute; par carte bancaire.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;En cas de s&amp;eacute;jour &amp;eacute;court&amp;eacute;, le prix correspondant au co&amp;ucirc;t du sejour reste int&amp;eacute;gralement acquis au propri&amp;eacute;taire. Le paiement du solde est &amp;agrave; verser &amp;agrave; l\'arriv&amp;eacute;e.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Les arriv&amp;eacute;es de font strictement entre 17 et 20 heures (sauf accord pr&amp;eacute;alable). Les d&amp;eacute;parts se font avant 12H00. Un suppl&amp;eacute;ment forfaitaire de 30 euros sera appliqu&amp;eacute; pour toute arriv&amp;eacute;e ou tout d&amp;eacute;part en dehors de ces horaires.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&lt;em&gt;&amp;bull; Au del&amp;agrave; de 3 nuit&amp;eacute;es reserv&amp;eacute;es (&amp;agrave; partir de la 4eme nuit), une remise de 10&amp;nbsp;&amp;euro; par nuit est accord&amp;eacute;e sur le tarif par nuit&amp;eacute;e sauf en Juillet et Aout&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;En Juillet et Aout, une majoration de 30&amp;nbsp;&amp;euro; par nuit sera appliqu&amp;eacute;e pour tout&amp;nbsp; s&amp;eacute;jour inf&amp;eacute;rieur &amp;agrave; 2 nuit&amp;eacute;es,&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;t&amp;eacute;l&amp;eacute;phoner&lt;/a&gt; &lt;a href=\&quot;reservation.php\&quot;&gt;r&amp;eacute;server par email&lt;/a&gt;&lt;/div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;Tarifs 2022 ROULOTTE &lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Prix en euros/nuit petits dejeuners offerts&lt;/p&gt;
&lt;/th&gt;&lt;th&gt;&lt;strong&gt;haute saison&lt;/strong&gt;&lt;/th&gt;&lt;th&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/th&gt;&lt;th&gt;&lt;strong&gt;basse saison&lt;/strong&gt;&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Roulotte&lt;/strong&gt; (1 ou 2 personnes)&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;&amp;nbsp;120 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;110 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;Tarifs 2022 GITE &lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Prix en euros/semaine&lt;/p&gt;
&lt;/th&gt;&lt;th&gt;
&lt;div&gt;&lt;strong&gt;Haute&lt;br /&gt; saison&lt;/strong&gt;&lt;/div&gt;
&lt;/th&gt;&lt;th&gt;
&lt;div&gt;&lt;strong&gt;&lt;strong&gt;Moyenne &lt;br /&gt; saison&lt;/strong&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/th&gt;&lt;th&gt;
&lt;div&gt;&lt;strong&gt;&lt;strong&gt;&lt;strong&gt;Basse &lt;br /&gt; saison&lt;/strong&gt;&lt;/strong&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Gite Maxi &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(7/8 pers maxi)&lt;/em&gt;&lt;br /&gt; 2&amp;nbsp; chambres avec douche&amp;nbsp; + WC, &lt;br /&gt; 1 chambre en mezzanine avec salle de bains + wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;p&gt;&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;2850&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+100 &amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1950&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80 &amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1250&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+50&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Gite Midi &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(4/5 pers maxi)&lt;/em&gt;&lt;br /&gt; 1&amp;nbsp; chambre avec douche&amp;nbsp; + WC, &lt;br /&gt; 1 chambre en mezzanine avec salle de bains + wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;&lt;strong&gt;1960&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&amp;nbsp;
&lt;p&gt;&lt;strong&gt;1350&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+60&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&amp;nbsp;
&lt;p&gt;&lt;strong&gt;990&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+40&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Gite Mini &lt;/strong&gt;&lt;br /&gt; &lt;em&gt;&amp;nbsp;(3 pers maxi)&lt;/em&gt;&lt;br /&gt; 1 chambre en mezzanine avec salle de bains &amp;nbsp;+ wc &lt;br /&gt; cuisine, salon, terrasses&lt;/p&gt;
&lt;p&gt;&lt;em&gt;forfait m&amp;eacute;nage&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&lt;strong&gt;Non Lou&amp;eacute;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&amp;nbsp;&lt;strong&gt;Non Lou&amp;eacute;&lt;/strong&gt;&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;&amp;nbsp;
&lt;p&gt;&lt;strong&gt;850 &amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+30&amp;nbsp;&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linge de maison fourni, lits faits &amp;agrave; l\'arriv&amp;eacute;e.&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Basse saison : reste de l\'ann&amp;eacute;e&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Moyenne saison : du 1er/04/22 au 01/07/2022 et du 17/09 au 30/09/2022, &amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Haute saison : du 1er/07 au 16/09/2022&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;En moyenne et basse saison, tarifs hors charges electricit&amp;eacute; (chauffage)&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;Tarifs 2022 MAZET &lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Prix en euros/nuit (sans petits dejeuners) - Minimum 3 nuits&lt;/p&gt;
&lt;/th&gt;&lt;th&gt;&lt;strong&gt;haute saison&lt;/strong&gt;&lt;/th&gt;&lt;th&gt;&lt;strong&gt;moyenne saison&lt;/strong&gt;&lt;/th&gt;&lt;th&gt;&lt;strong&gt;basse saison&lt;/strong&gt;&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&amp;nbsp;maisonnette independante pour 2 personnes&lt;/p&gt;
&lt;p&gt;1 chambre avec Tv et petit coin salon, 1 cuisine et son espace repas,&lt;/p&gt;
&lt;p&gt;1 salle de douche avec WC, terrasse avec salon de jardin et de repas,&lt;/p&gt;
&lt;p&gt;forfait m&amp;eacute;nage&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;130 &amp;euro;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;
&lt;p&gt;110 &amp;euro;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=\&quot;text-align: center;\&quot;&gt;95 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;Linge de maison fourni, lits faits &amp;agrave; l\'arriv&amp;eacute;e.&lt;/div&gt;
&lt;div&gt;possibilit&amp;eacute; de petit dejeuner : +10&amp;euro;/personne&lt;/div&gt;
&lt;div&gt;&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Basse saison : reste de l\'ann&amp;eacute;e&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Moyenne saison : du 1er/04 au 01/07/22 et du 17/09 au 30/09/22 (minimum 3 nuits)&amp;nbsp;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Haute saison : du 1er/07 au 16/09/2022 (minimum 5 nuits)&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Remise de 10% pour un sejour de minimum 7 nuits en basse et moyenne saison&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;t&amp;eacute;l&amp;eacute;phoner&lt;/a&gt; &lt;a href=\&quot;reservation.php\&quot;&gt;r&amp;eacute;server par email&lt;/a&gt;&lt;/div&gt;";

$champ_2="&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;&lt;th&gt;&lt;strong&gt;Rates 2022 AMANDARI (BREAKFASTS INCLUDED)&lt;/strong&gt;&lt;/th&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;high season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;from 01/07 to 16/09/2022&lt;/strong&gt;&lt;/p&gt;
&lt;/th&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;mid season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;from 01/04 to 30/06&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;from 17/09 to 30/09/22&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;amp; from 22/10 to 13/11/22&lt;/strong&gt;&lt;/p&gt;
&lt;/th&gt;&lt;th&gt;&lt;strong&gt;low season&lt;/strong&gt;&lt;/th&gt;&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Room Amande ( 2 persons)&lt;/td&gt;
&lt;td&gt;140&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;td&gt;130 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td&gt;120&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Room Romarin ( 2 persons );extra bed&lt;/td&gt;
&lt;td&gt;140&amp;nbsp;&amp;euro; + 30&amp;euro;&lt;/td&gt;
&lt;td&gt;130+ 25 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td&gt;120 &amp;euro; +20&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Room Lavande ( 2 persons )&lt;/td&gt;
&lt;td&gt;140 &amp;euro; &amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;125 &amp;euro;&lt;/td&gt;
&lt;td&gt;120 &amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Room Olive ( 1 or 2 persons )&lt;/td&gt;
&lt;td&gt;120 &amp;euro;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;95 - 110 &amp;euro;&lt;/td&gt;
&lt;td&gt;90-100&amp;nbsp;&amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Family Room ( 3 or 4 persons)two communicating rooms&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;200&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;185-195 &amp;euro;&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;180-190&amp;nbsp;&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;ul&gt;
&lt;ul&gt;
&lt;li&gt;Dinner upon reservation 6 guests requested : 35 &amp;euro;&lt;/li&gt;
&lt;li&gt;Dogs allowed with previous agreement :5/10&amp;nbsp;&amp;euro; / day ( according to size )&lt;/li&gt;
&lt;/ul&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;em&gt;&lt;strong&gt;&amp;bull; Over&amp;nbsp;&lt;/strong&gt;&lt;strong&gt;&amp;nbsp;3 nights booked, a special discount of &amp;nbsp;10&amp;nbsp;&amp;euro; / night will be granted except in July and August.&lt;/strong&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;nbsp;In July and August, a 30&amp;euro; overcharge/night will be asked for any stay under 2 nights.&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;&amp;nbsp;When booking, a deposit of 30% of the stay, with a minimum of one night will be required by credit card.&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;phone&lt;/a&gt; &lt;a href=\&quot;reservation-en.php\&quot;&gt;book by email&lt;/a&gt;&lt;/div&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;&lt;th&gt;
&lt;p&gt;&lt;strong&gt;Rates 2022 Caravan &lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Price in EUR / night breakfasts offered&lt;/p&gt;
&lt;/th&gt;
&lt;td&gt;
&lt;div&gt;&lt;strong&gt;high season&lt;br /&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;th&gt;
&lt;div&gt;&lt;strong&gt;mid season&lt;/strong&gt;&lt;/div&gt;
&lt;/th&gt;
&lt;td&gt;&lt;strong&gt;low season&lt;br /&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Gipsy Caravan&lt;/strong&gt; (1 or 2 people)&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;140&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;120 &amp;euro;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;110 &amp;euro;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;p&gt;&lt;strong&gt;The rooms are non smoking.&lt;/strong&gt; &lt;br /&gt;&lt;br /&gt;&lt;/p&gt;
&lt;p&gt;In case of shortened stay, the price for the cost of living remains entirely due to &amp;nbsp;the owner. &lt;br /&gt;The balance has to be paid upon arrival.&lt;/p&gt;
&lt;p&gt;Arrivals are strictly between 5:00 p.m. and 8:00 p.m (except prior agreement). Departures are before 12:00.&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt;if your arrival or departure is out of this time, we will ask for an additional fee : 30&amp;nbsp;&amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Rates 2022 COTTAGE &lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Price in EUR / week&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;div&gt;&lt;strong&gt;High&lt;br /&gt; season&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;div&gt;&lt;strong&gt;&lt;strong&gt;Middle&amp;nbsp;&lt;br /&gt; season &lt;/strong&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;div&gt;&lt;strong&gt;&lt;strong&gt;&lt;strong&gt;Low &lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Maxi cottage&lt;/strong&gt; &lt;br /&gt; &lt;em&gt;(7/8 people max)&lt;/em&gt; &lt;br /&gt; 2 bedrooms with shower and toilet, &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;2850&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+100&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;1950&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;1250&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+50&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;&amp;nbsp;Midi cottage&lt;/strong&gt;&lt;br /&gt; &lt;em&gt;(4/5 people max)&lt;/em&gt; &lt;br /&gt; 1 bedroom with shower and toilet, &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;1960&amp;nbsp;&amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+80&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;1350&amp;nbsp;&amp;euro;&lt;/strong&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+60&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;strong&gt;990 &amp;euro;&lt;/strong&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+40&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;Mini Cottage&lt;/strong&gt; &lt;br /&gt; &lt;em&gt;(3 people max)&lt;/em&gt; &lt;br /&gt; 1 mezzanine bedroom with bathroom + wc &lt;br /&gt; kitchen, lounge, terraces&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Housecleaning&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;Not Rented&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;strong&gt;Not Rented&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;
&lt;p&gt;&lt;strong&gt;850 &amp;euro;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;+30&amp;euro;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linen provided - Beds are prepared upon arrival&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Low season : other periods&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Middle season : from 01/04 to 30/06/2022, from 17/09 to 30/09, from 22/10 TO 13/11/22&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;High season : from 01/07/2021 to 16/09/2022&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Medium and low season rates excluding &amp;nbsp;electricity charges (heating)&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;&lt;strong&gt;Rates &lt;/strong&gt;2022 MAZET&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Price in EUR / night (without breakfasts), minimum 3 nights stay&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong&gt;High&lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong&gt;Middle&amp;nbsp;&lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong&gt;Low &lt;br /&gt; season&lt;/strong&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&amp;nbsp;independant cottage for 2 persons&lt;/p&gt;
&lt;p&gt;1 bedroom with TV and lounge corner, 1 kitchen&amp;nbsp; sand meal room ,&lt;/p&gt;
&lt;span class=\&quot;tlid-translation translation\&quot; lang=\&quot;en\&quot;&gt;&lt;span title=\&quot;\&quot;&gt;1 shower room with WC, terrace with garden furniture and dining,&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;&lt;span title=\&quot;\&quot;&gt;cleaning fee&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;130 &amp;euro;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;+30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;110 &amp;euro;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;+30 &amp;euro;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=\&quot;4\&quot;&gt;
&lt;div&gt;
&lt;p&gt;Linen provided - Bed is prepared upon arrival (possibility to add a baby bed free)&lt;/p&gt;
&lt;p&gt;breakfast may be proposed : +10&amp;euro;/person&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;div&gt;&lt;strong&gt;Low season : other periods&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Middle season : from 01/04 to 30/06/2022, from 17/09 to 30/09, from 22/10 TO 13/11/22&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;High season : from 01/07/2021 to 16/09/2022&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;Medium and low season rates excluding &amp;nbsp;electricity charges (heating)&lt;/strong&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;&lt;/div&gt;
&lt;div&gt;&lt;strong&gt;10% discount over 7 nights stay in low and middle seasons&lt;/strong&gt;&lt;/div&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&amp;nbsp;&lt;/div&gt;
&lt;div class=\&quot;reserver\&quot;&gt;&lt;a href=\&quot;tel:+33.494437920\&quot;&gt;phone&lt;/a&gt; &lt;a href=\&quot;reservation-en.php\&quot;&gt;book by email&lt;/a&gt;&lt;/div&gt;";

$champ_3="";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

?>
